export type Product = {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  clinicalCopy: string;
  price: number;
  cost: number;
  category: "vibe" | "ring" | "lube" | "bullet" | "bundle";
  image: string;
  badge?: string;
  bestFor?: string;
  stripePriceId?: string;
  sku?: string;
  hidden?: boolean;
};

/** Focus mode: only these two SKUs shown on storefront. */
export const FOCUS_SLUGS = ["her-rose-therapy", "her-pulse-essential"] as const;

export const PRODUCTS: Product[] = [
  {
    id: "prod_rose",
    slug: "her-rose-therapy",
    name: "Her Rose Therapy",
    shortName: "Rose Therapy",
    tagline: "#1 Women's Choice",
    description: "The rose-shaped design women choose most. Discreet, body-safe, and clinically trusted for satisfaction and comfort.",
    clinicalCopy: "78% satisfaction in trials. Discreet shipping, free over $50. Medical-grade silicone, waterproof, rechargeable.",
    price: 29,
    cost: 2.8,
    category: "vibe",
    image: "/products/rose.png",
    badge: "Rose Gold",
    bestFor: "Beginners and everyday wellness.",
    sku: "ROSE-001",
  },
  {
    id: "prod_pulse",
    slug: "her-pulse-essential",
    name: "Her Pulse Essential",
    shortName: "Pulse Essential",
    tagline: "Essential pulse technology",
    description: "Compact, powerful pulse technology. Travel-ready and discreet.",
    clinicalCopy: "Ergonomic fit, adjustable stimulation. Used in wellness settings. Discreet shipping.",
    price: 19,
    cost: 5,
    category: "vibe",
    image: "/products/pulse.png",
    badge: "Backup",
    bestFor: "On-the-go and backup.",
    sku: "PULSE-001",
  },
  {
    id: "prod_1",
    slug: "her-pulse-therapy",
    hidden: true,
    name: "Her Pulse Therapy",
    shortName: "Pulse Therapy",
    tagline: "Clinically tested pleasure technology",
    description: "Clinically tested pleasure technology designed to enhance sensitivity and response.",
    clinicalCopy: "Engineered for ergonomic fit and consistent, adjustable stimulation. Used in clinical settings for wellness and stress relief.",
    price: 39,
    cost: 26,
    category: "vibe",
    image: "/products/pulse.png",
    badge: "Bestseller",
    bestFor: "Powerful stimulation and fast results.",
  },
  {
    id: "prod_2",
    slug: "her-rhythm-ring",
    name: "Her Rhythm Ring",
    shortName: "Rhythm Ring",
    tagline: "Wearable wellness support",
    description: "Wearable wellness support for shared experiences.",
    clinicalCopy: "Wearable technology designed for biofeedback and relaxation. Discreet, waterproof, rechargeable.",
    price: 49,
    cost: 33,
    category: "ring",
    image: "/products/ring.png",
    badge: "10K+ Sold",
    bestFor: "Hands-free intimacy.",
    hidden: true,
  },
  {
    id: "prod_3",
    slug: "her-daily-essential",
    name: "Her Daily Essential",
    shortName: "Daily Essential",
    tagline: "Body-friendly lubricant",
    description: "Body-friendly lubricant formulated for comfort and balance.",
    clinicalCopy: "Dermatologist-tested, hypoallergenic. No parabens, no glycerin. Compatible with condoms and toys.",
    price: 19,
    cost: 11,
    category: "lube",
    image: "/products/lube.png",
    bestFor: "Everyday hydration and smoothness.",
    hidden: true,
  },
  {
    id: "prod_bundle_1",
    slug: "starter-bundle",
    name: "Starter Bundle",
    shortName: "Starter Bundle",
    tagline: "Pulse Therapy + Daily Essential",
    description: "The perfect first experience — enhanced stimulation with body-safe comfort.",
    clinicalCopy: "Our bestselling vibrator plus our body-friendly lubricant. Save 10% when you bundle.",
    price: 52.2,
    cost: 37,
    category: "bundle",
    image: "/products/bundle.png",
    badge: "Save 10%",
    hidden: true,
  },
  {
    id: "prod_4",
    slug: "her-quiet-pulse",
    name: "Her Quiet Pulse",
    shortName: "Quiet Pulse",
    tagline: "Whisper-quiet design",
    description: "Ultra-quiet compact vibrator. Perfect for travel and discretion.",
    clinicalCopy: "Low-decibel motor with 5 intensity levels. Rechargeable USB, travel lock.",
    price: 34,
    cost: 22,
    category: "vibe",
    image: "/products/quiet.png",
    hidden: true,
  },
  {
    id: "prod_5",
    slug: "her-silk-ring",
    name: "Her Silk Ring",
    shortName: "Silk Ring",
    tagline: "Silicone comfort",
    description: "Flexible silicone ring with gentle stimulation. One size fits most.",
    clinicalCopy: "Medical-grade silicone. Easy to clean, waterproof. Designed for comfort during extended wear.",
    price: 44,
    cost: 29,
    category: "ring",
    image: "/products/silk-ring.png",
    hidden: true,
  },
  {
    id: "prod_6",
    slug: "her-hydrate-gel",
    name: "Her Hydrate Gel",
    shortName: "Hydrate Gel",
    tagline: "Long-lasting comfort",
    description: "Long-lasting gel formula. A little goes a long way.",
    clinicalCopy: "Water-based, no sticky residue. Recommended by wellness practitioners.",
    price: 22,
    cost: 12,
    category: "lube",
    image: "/products/hydrate.png",
  },
  {
    id: "prod_7",
    slug: "her-bullet-mini",
    name: "Her Bullet Mini",
    shortName: "Bullet Mini",
    tagline: "Pocket-sized power",
    description: "Small but powerful bullet vibrator. Discreet and travel-ready.",
    clinicalCopy: "Precision motor, 3 speeds. USB rechargeable, discreet storage pouch included.",
    price: 24,
    cost: 15,
    category: "bullet",
    image: "/products/bullet.png",
    hidden: true,
  },
  {
    id: "prod_8",
    slug: "her-wave-therapy",
    name: "Her Wave Therapy",
    shortName: "Wave Therapy",
    tagline: "Wave technology",
    description: "Curved design with wave motion. Targets sensitive areas with precision.",
    clinicalCopy: "Ergonomic curve based on clinical feedback. Waterproof, rechargeable.",
    price: 42,
    cost: 28,
    category: "vibe",
    image: "/products/wave.png",
    hidden: true,
  },
  {
    id: "prod_9",
    slug: "her-duo-ring",
    name: "Her Duo Ring",
    shortName: "Duo Ring",
    tagline: "Dual stimulation",
    description: "Dual-motor ring for shared or solo use. App connectivity optional.",
    clinicalCopy: "Dual motors with independent control. Medical-grade silicone, waterproof.",
    price: 54,
    cost: 36,
    category: "ring",
    image: "/products/duo-ring.png",
    hidden: true,
  },
  {
    id: "prod_10",
    slug: "her-silk-touch",
    name: "Her Silk Touch",
    shortName: "Silk Touch",
    tagline: "Silky smooth",
    description: "Silicone-safe water-based lubricant. No silicone in formula.",
    clinicalCopy: "Compatible with all silicone toys. Odorless, non-staining.",
    price: 18,
    cost: 10,
    category: "lube",
    image: "/products/silk-touch.png",
    hidden: true,
  },
  {
    id: "prod_11",
    slug: "her-bullet-plus",
    name: "Her Bullet Plus",
    shortName: "Bullet Plus",
    tagline: "Stronger intensity",
    description: "Upgraded bullet with stronger motor and 7 patterns.",
    clinicalCopy: "Higher torque motor, multiple patterns. USB-C rechargeable.",
    price: 29,
    cost: 18,
    category: "bullet",
    image: "/products/bullet-plus.png",
    hidden: true,
  },
  {
    id: "prod_12",
    slug: "her-bliss-vibe",
    name: "Her Bliss Vibe",
    shortName: "Bliss Vibe",
    tagline: "Full-body relaxation",
    description: "Larger wand-style vibrator for deep, rumbling stimulation.",
    clinicalCopy: "Designed for muscle relaxation and stress relief. Used in wellness routines.",
    price: 46,
    cost: 30,
    category: "vibe",
    image: "/products/bliss.png",
    hidden: true,
  },
  {
    id: "prod_13",
    slug: "her-snap-ring",
    name: "Her Snap Ring",
    shortName: "Snap Ring",
    tagline: "Quick release",
    description: "Snap-on design for easy cleaning. Waterproof and durable.",
    clinicalCopy: "Quick-release mechanism. Medical-grade materials, dishwasher-safe parts.",
    price: 39,
    cost: 26,
    category: "ring",
    image: "/products/snap-ring.png",
    hidden: true,
  },
  {
    id: "prod_14",
    slug: "her-aroma-free",
    name: "Her Aroma-Free",
    shortName: "Aroma-Free",
    tagline: "Sensitive skin",
    description: "Fragrance-free, dye-free lubricant for sensitive skin.",
    clinicalCopy: "Dermatologist-tested for sensitive skin. No common allergens.",
    price: 21,
    cost: 11,
    category: "lube",
    image: "/products/aroma-free.png",
    hidden: true,
  },
  {
    id: "prod_15",
    slug: "her-bullet-touch",
    name: "Her Bullet Touch",
    shortName: "Bullet Touch",
    tagline: "Touch-sensitive",
    description: "Touch-sensitive bullet that responds to pressure. Innovative control.",
    clinicalCopy: "Pressure-sensitive intensity. Rechargeable, travel lock.",
    price: 27,
    cost: 17,
    category: "bullet",
    image: "/products/bullet-touch.png",
    hidden: true,
  },
];

/** Visible on storefront (focus mode: 2 SKUs). */
export function getVisibleProducts(): Product[] {
  return PRODUCTS.filter((p) => !p.hidden);
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
